### ISSUE TITLE
No Preventive Measures

### ISSUE THREAD

**Issue by varunpareek690** [LuizBoina/dragon-gpt#1]
The model is well-trained to provide threat analysis along with the description of threat, but unless there is nothing to do, the user will not take any step towards prevention of these threats

**Comment by LuizBoina** [comment]
Hi, @varunpareek690, I really appreciate your PR and I'll test it, but before that can you remove your leaked openai key from the commit? I also recommend deleting this key and generating another one for security reasons.

**Comment by varunpareek690** [comment]
I deeply regret for my nuisance sir and thank you for indicating me my mistake!
